### ISSUE TITLE
clear preferences

### ISSUE THREAD

**Issue by derohimat** [jibbo/SweetPrefs#1]
how to clear preferences ?

**Comment by jibbo** [comment]
Excellent question! Sadly, i forgot to add a way to do this natively from within an IStorage. Therefore, you’ll have to do it the Android way and retrieve from a context the Shared Preference with your chosen name and call the clear() method upon those. I will include this behaviour in this library sooner or later but If you are willing, you could extend the IStorage class and also the SharedPreferenceStorage one to add this feature and I would be thrilled to review and accept you Pull Request!

**Comment by derohimat** [comment]
I see on your *dev* branch already have reset function :D

**Comment by jibbo** [comment]
Yes, Today I had some free time and I decided to implement it, I'm waiting for the mod to be approved by bintray and then I'll move it to master.
